# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Sharly Chess
email: contact@sharly-chess.com
description:
  en: Sharly Chess is a free and open-source tool for managing chess tournaments.
  fr: Sharly Chess est un outil gratuit et open-source pour la gestion de tournois d’échecs.
baseurl: "" # the subpath of your site, e.g. /blog
permalink: :categories/:year/:month/:day/:slug:output_ext
url: "https://sharly-chess.github.io" # the base hostname & protocol for your site, e.g. http://example.com
version: 2.6.0

parallel_localization: false

# Build settings
theme: just-the-docs
plugins:
  - jekyll-feed

color_scheme: sc

languages: ["en","fr"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css", "public", " sitemap"]
lang_from_path: true
langsep: "|"
search_enabled: true
excerpt_separator: <!--more-->
nav_external_links:
  - title: GitHub
    url: https://github.com/Sharly-Chess/sharly-chess
    hide_icon: false
    opens_in_new_tab: true

callouts:
  note:
    color: blue
  tip:
    color: yellow
  warning:
    color: red

sass:
  quiet_deps: true # https://github.com/just-the-docs/just-the-docs/issues/1541
  silence_deprecations: ['import'] # https://github.com/just-the-docs/just-the-docs/issues/1607

collections:
  footer-links:
    output: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
